// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCObUJMbM4iP8n2lg_XM4yjVrdC0hNvWTY',
    appId: '1:328650388720:web:0feac1dfdd4304d417be35',
    messagingSenderId: '328650388720',
    projectId: 'tiendaonline-71adf',
    authDomain: 'tiendaonline-71adf.firebaseapp.com',
    storageBucket: 'tiendaonline-71adf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9OHiT6gUVBFLB7UJd2KYu7E2zca5Emd0',
    appId: '1:328650388720:android:657b4e842b63723b17be35',
    messagingSenderId: '328650388720',
    projectId: 'tiendaonline-71adf',
    storageBucket: 'tiendaonline-71adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1P08lruTQS7ic7Y5KJx7cCSSdky-tbis',
    appId: '1:328650388720:ios:a3a3f9ee1867468217be35',
    messagingSenderId: '328650388720',
    projectId: 'tiendaonline-71adf',
    storageBucket: 'tiendaonline-71adf.firebasestorage.app',
    iosBundleId: 'com.example.tiendaonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1P08lruTQS7ic7Y5KJx7cCSSdky-tbis',
    appId: '1:328650388720:ios:a3a3f9ee1867468217be35',
    messagingSenderId: '328650388720',
    projectId: 'tiendaonline-71adf',
    storageBucket: 'tiendaonline-71adf.firebasestorage.app',
    iosBundleId: 'com.example.tiendaonline',
  );
}
